### ISSUE TITLE
KeyError at /duo/login/ '_auth_user_backend'

### ISSUE THREAD

**Issue by CitadelOfBlairs** [Elemnir/django-duo-auth#3]
I'm just documenting my fix to this issue in case other devs run into it.

I had a user bookmark my app's `/duo/login` page instead of `/accounts/login`. After their session expired, they visited `/duo/login` without first authenticating to the Django 3.1.5 app, leading to an unhandled error:

```
Traceback (most recent call last):
  File "/home/testappuser/.venv-testapp/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/testappuser/.venv-testapp/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/testappuser/.venv-testapp/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/testappuser/.venv-testapp/lib/python3.7/site-packages/sentry_sdk/integrations/django/views.py", line 36, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/testappuser/.venv-testapp/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/testappuser/.venv-testapp/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/testappuser/.venv-testapp/lib/python3.7/site-packages/duo_auth/views.py", line 27, in get
    auth_backend = request.session[BACKEND_SESSION_KEY]
  File "/home/testappuser/.venv-testapp/lib/python3.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in __getitem__
    return self._session[key]

Exception Type: KeyError at /duo/login/
Exception Value: '_auth_user_backend'
Request information:
USER: AnonymousUser

GET: No GET data

POST: No POST data

FILES: No FILES data
```

I think adding the `login_required` decorator to DuoAuthView in `src/duo_auth/urls.py` resolves the error but could break django-duo-auth for other use cases. I ended up installing `django-decorator-include` and updating my app's urls.py to force a successful user authentication before DuoAuthView:

```
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from decorator_include import decorator_include

urlpatterns = [
    # ...
    path('duo/',  decorator_include(login_required, 'duo_auth.urls')),
]
```

**Comment by Elemnir** [comment]
I think it's fair to say that the Duo Auth component depends on _some_ first stage authentication being in place. I think adding the login_required decorator would be appropriate.  If you'd like, I'd accept a pull request making this change.
